### ISSUE TITLE
RE: Variability

### ISSUE THREAD

**Issue by BB1464** [cran/variability#1]
Good morning there all,
     Please I used the variability package to run phenotypic and genotypic correlation for 24 traits.
 The results I am getting in markdown is breaking.
Please is there any way I can let the variability package know that my output should be Rmarkdown?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
